---
AWSTemplateFormatVersion: 2010-09-09
Description: Moodle cache cluster

Parameters:
  CacheEngineType:
    AllowedValues:
      - Redis
      - Memcached
    Default: Memcached
    Description: Cache engine to use.
    Type: String
  CacheUsageType:
    AllowedValues:
      - application
      - session
    Default: session
    Description: Session or application caching.
    Type: String
  ElastiCacheClusterName:
    AllowedPattern: ^([a-zA-Z0-9]*)$
    Description: ElastiCache cluster name.
    Type: String
  ElastiCacheNodeType:
    AllowedValues:
      - cache.t2.micro
      - cache.t2.small
      - cache.t2.medium
      - cache.t3.micro
      - cache.t3.small
      - cache.t3.medium
      - cache.t4g.micro
      - cache.t4g.small
      - cache.t4g.medium
      - cache.m4.large
      - cache.m4.xlarge
      - cache.m4.2xlarge
      - cache.m4.4xlarge
      - cache.m4.10xlarge
      - cache.m5.large
      - cache.m5.xlarge
      - cache.m5.2xlarge
      - cache.m5.4xlarge
      - cache.m5.12xlarge
      - cache.m5.24xlarge
      - cache.m6g.large
      - cache.m6g.xlarge
      - cache.m6g.2xlarge
      - cache.m6g.4xlarge
      - cache.m6g.8xlarge
      - cache.m6g.12xlarge
      - cache.m6g.16xlarge
      - cache.r4.large
      - cache.r4.xlarge
      - cache.r4.2xlarge
      - cache.r4.4xlarge
      - cache.r4.8xlarge
      - cache.r4.16xlarge
      - cache.r5.large
      - cache.r5.xlarge
      - cache.r5.2xlarge
      - cache.r5.4xlarge
      - cache.r5.12xlarge
      - cache.r5.24xlarge
      - cache.r6g.large
      - cache.r6g.xlarge
      - cache.r6g.2xlarge
      - cache.r6g.4xlarge
      - cache.r6g.8xlarge
      - cache.r6g.12xlarge
      - cache.r6g.16xlarge
      - cache.r6gd.xlarge
      - cache.r6gd.2xlarge
      - cache.r6gd.4xlarge
      - cache.r6gd.8xlarge
      - cache.r6gd.12xlarge
      - cache.r6gd.16xlarge
    ConstraintDescription: Must be a valid Amazon ElastiCache node type.
    Default: cache.r6g.large
    Description: ElastiCache cluster node type.
    Type: String
  ElastiCacheSecurityGroup:
    Description: ElastiCache Security Group.
    Type: AWS::EC2::SecurityGroup::Id
  NumberOfSubnets:
    AllowedValues:
    - 1
    - 2
    - 3
    Default: 2
    Description: Number of subnets. This must match your selections in the list of subnets below.
    Type: String 
  Subnet:
    Description: Select existing subnets. The number selected must match the number of subnets above. Subnets selected must be in separate AZs.
    Type: List<AWS::EC2::Subnet::Id>
  ProjectName:
    AllowedPattern: ^([a-zA-Z0-9]*)$
    Default: App
    Description: Moodle Project Name
    Type: String

Conditions:
  UseRedis: !Equals [!Ref CacheEngineType, Redis]
  UseMemcached: !Equals [!Ref CacheEngineType, Memcached]
  NumberOfSubnets1: !Equals [ 1, !Ref NumberOfSubnets ]
  NumberOfSubnets2: !Equals [ 2, !Ref NumberOfSubnets ]

Resources:
  ElastiCacheClusterRedis:
    Condition: UseRedis
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: !Ref ElastiCacheClusterName
      ReplicationGroupDescription: !Ref ElastiCacheClusterName
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: true
      AutoMinorVersionUpgrade: true
      MultiAZEnabled: true
      CacheNodeType: !Ref ElastiCacheNodeType
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      SecurityGroupIds:
        - !Ref ElastiCacheSecurityGroup
      Engine: redis
      NumCacheClusters: !Ref NumberOfSubnets

  ElastiCacheClusterMemcached:
    Condition: UseMemcached
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AZMode: cross-az
      CacheNodeType: !Ref ElastiCacheNodeType
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      ClusterName: !Ref ElastiCacheClusterName
      Engine: memcached
      NumCacheNodes: !Ref NumberOfSubnets
      VpcSecurityGroupIds:
        - !Ref ElastiCacheSecurityGroup      
 
  ElastiCacheSubnetGroup: 
    Type: AWS::ElastiCache::SubnetGroup
    Properties: 
      CacheSubnetGroupName: !Join [ '', [ !Ref ElastiCacheClusterName, SubnetGroup ] ]
      Description: ElastiCache Subnet Group for Moodle
      SubnetIds: !If [ NumberOfSubnets1, [ !Select [ 0, !Ref Subnet ] ],
        !If [ NumberOfSubnets2, [ !Select [ 0, !Ref Subnet ], !Select [ 1, !Ref Subnet ] ],
        [ !Select [ 0, !Ref Subnet ], !Select [ 1, !Ref Subnet ], !Select [ 2, !Ref Subnet ] ] ] ]

  ElastiCacheClusterEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ '/Moodle/',!Ref ProjectName, '/Cache/', !Ref CacheUsageType, '/ElastiCacheClusterEndpoint' ] ]
      Description: ElastiCache Cluster Endpoint
      Type: String
      Value: !If [UseRedis, !Join [ ':', [!GetAtt ElastiCacheClusterRedis.PrimaryEndPoint.Address, !GetAtt ElastiCacheClusterRedis.PrimaryEndPoint.Port]],
        !Join [ ':', [!GetAtt ElastiCacheClusterMemcached.ConfigurationEndpoint.Address, !GetAtt ElastiCacheClusterMemcached.ConfigurationEndpoint.Port]] ]

  ElastiCacheEngine:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ '/Moodle/',!Ref ProjectName, '/Cache/', !Ref CacheUsageType, '/Engine' ] ]
      Description: !Sub ElastiCache Engine Type (${CacheUsageType})
      Type: String
      Value: !Ref CacheEngineType

Outputs:
  ElastiCacheClusterEndpointAddress:
    Value: !If [UseRedis, !Join [ ':', [!GetAtt ElastiCacheClusterRedis.PrimaryEndPoint.Address, !GetAtt ElastiCacheClusterRedis.PrimaryEndPoint.Port]],
      !Join [ ':', [!GetAtt ElastiCacheClusterMemcached.ConfigurationEndpoint.Address, !GetAtt ElastiCacheClusterMemcached.ConfigurationEndpoint.Port]] ]
